# This is a basic workflow to help you get started with Actions

name: Chained workflow 1

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      version:
        description: 'Version tag used for the deployment'
        default: 'v0.0.0'
        required: true
        type: string
    secrets:
      credentials:
        description: 'A secret containing credentials'
        required: false


          

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job_workflow_1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "I was triggered by 'workflow_call' event"
          echo "This is a new version of the workflow, first updated and tested in branch 'feature-xyz'"
          echo "deployment version: ${{ inputs.version }}"
          echo "Credentials were passed as secret (Warning: this actually epxoses the secret!): ${{ secrets.credentials }}"
          echo
          echo "Checking if file was cloned..."
          cat ./this_is_my_code.txt
